# volumes:
volumes:
    postgres-data:
        external: true
    # pg-admin:  DONT NEED?
    #     external: true DONT NEED?
    # other volumes...

services:
  fastapi-accounts:
    build:
        context: ./fastapi-accounts
        dockerfile: ./Dockerfile.dev
    ports:
        - 8001:8000
    volumes:
        - ./fastapi-accounts:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: 4ff6a7021b505ebc0c182005e8e8845e19b428f86285a51e5dbb1763e209de4f
  fastapi-quiz:
    build:
        context: ./fastapi-quiz
        dockerfile: ./Dockerfile.dev
    ports:
        - 8002:8000
    volumes:
        - ./fastapi-quiz:/app
    environment:
      DATABASE_URL: postgresql://quiz:password@postgres/quiz
      WAIT_HOSTS: postgres:5432
      SIGNING_KEY: 4ff6a7021b505ebc0c182005e8e8845e19b428f86285a51e5dbb1763e209de4f
  fastapi-playlist:
    build:
        context: ./fastapi-playlists
        dockerfile: ./Dockerfile.dev
    ports:
        - 8003:8000
    volumes:
        - ./fastapi-playlists:/app
    environment:
      DATABASE_URL: postgresql://playlists:password@postgres/playlists
      WAIT_HOSTS: postgres:5432
  postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=accounts,playlists,quiz
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    # other services, too...

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8001
      REACT_APP_ACCOUNTS_API_HOST: http://localhost:8001
      REACT_APP_PLAYLIST_API_HOST: http://localhost:8003
      REACT_APP_QUIZ_API_HOST: http://localhost:8002
      REACT_APP_PUBLIC_URL: http://localhost:3000
