# volumes:
volumes:
    postgres-data:
        external: true
    # other volumes...

services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  fastapi-accounts:
    build:
        context: ./fastapi-accounts
        dockerfile: ./Dockerfile.dev
    ports:
        - 8001:8000
    volumes:
        - ./fastapi-accounts:/app
    environment:
      DATABASE_URL: postgresql://accounts:password@postgres/accounts
      WAIT_HOSTS: postgres:5432
  postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=accounts,playlists
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    # other services, too...

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
